### ISSUE TITLE
Files missing from Widget Options v 3.8

### ISSUE THREAD

**Issue by chrisselwyn** [WidgetOptions/widget-options#123]
I have just installed Widget Options 3.8 and it seems that there are 2 files missing from the installation that I get from the Wordpress plugin installation site.
The 2 files are 

- includes/widgets/option-tabs/days-dates.php
- includes/widgets/option-tabs/styling.php

I have downloaded them from your github and uploaded them to my site and the plugin now appears to be working again.
Could you please ensure that these files are included in the distribution?

Chris

**Comment by AntiTcb** [comment]
Seconded, had my admin panel throw fatal exceptions because of this.

**Comment by hollisterca** [comment]
I get "There has been a critical error on this website. Please check your site admin email inbox for instructions." just trying to login

**Comment by medgedecastro** [comment]
Fixed on version 3.8.1
